// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://locwmhzldgiyyucfkryc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY3dtaHpsZGdpeXl1Y2ZrcnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMjg3NzksImV4cCI6MjA1MDkwNDc3OX0.dKG_E2sBtr0nTh89lsWTZXQEtaRs6jQq5G6Sr1xsuSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);